import { User, Post, UserStory, Reel, Note, ChatThread, Product, NotificationItem } from './types';

export const CURRENT_USER: User = {
  id: 'user_current',
  username: 'alex_creator',
  fullName: 'Alex Rivers',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
  bio: 'Visual designer & photographer 📸 \nExploring light, geometry & urban landscapes.\nCoffee enthusiast ☕ | Tokyo • NYC',
  isVerified: true,
  category: 'Digital Creator',
  website: 'alexrivers.design',
  followersCount: 18420,
  followingCount: 540,
  postsCount: 142,
  isFollowing: false,
};

export const MOCK_USERS: Record<string, User> = {
  sophia: {
    id: 'user_sophia',
    username: 'wanderlust_sophia',
    fullName: 'Sophia Bennett',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    bio: 'Traveling the globe one sunset at a time ✈️ 42 countries and counting',
    isVerified: true,
    category: 'Travel & Lifestyle',
    followersCount: 142000,
    followingCount: 312,
    postsCount: 521,
    isFollowing: true,
  },
  marcus: {
    id: 'user_marcus',
    username: 'marcus_creates',
    fullName: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    bio: 'Architecture & minimalist interior design 🏛️ Curating space & shadow',
    isVerified: false,
    category: 'Architecture',
    followersCount: 68400,
    followingCount: 420,
    postsCount: 284,
    isFollowing: true,
  },
  tokyo: {
    id: 'user_tokyo',
    username: 'tokyo_lens',
    fullName: 'Kenji Takahashi',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    bio: 'Neon nights & street photography in Tokyo 🌃 Leica M11 shooter',
    isVerified: true,
    category: 'Photographer',
    followersCount: 95300,
    followingCount: 189,
    postsCount: 412,
    isFollowing: true,
  },
  luna: {
    id: 'user_luna',
    username: 'luna_designs',
    fullName: 'Luna Chen',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    bio: 'Ceramics, coffee wares & handcrafted slow living 🏺 Studio in Brooklyn',
    isVerified: false,
    category: 'Art & Craft',
    followersCount: 34100,
    followingCount: 415,
    postsCount: 189,
    isFollowing: false,
  },
  chef: {
    id: 'user_chef',
    username: 'chef_marco',
    fullName: 'Marco DeLuca',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    bio: 'Modern Tuscan culinary artistry 🍝 Chef owner at Trattoria Stella',
    isVerified: true,
    category: 'Culinary',
    followersCount: 88900,
    followingCount: 602,
    postsCount: 340,
    isFollowing: true,
  },
};

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post_1',
    author: MOCK_USERS.sophia,
    media: [
      {
        id: 'm1_1',
        url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1000&auto=format&fit=crop&q=80',
        type: 'image',
      },
      {
        id: 'm1_2',
        url: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1000&auto=format&fit=crop&q=80',
        type: 'image',
      },
      {
        id: 'm1_3',
        url: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1000&auto=format&fit=crop&q=80',
        type: 'image',
      },
    ],
    caption: 'Chasing golden hour across the alpine ridge. Swipe for the quiet reflections in the emerald lake 🌲✨ Nature never misses a beat.',
    location: 'Dolomites, Italy',
    timestamp: '2 hours ago',
    likesCount: 14280,
    isLiked: false,
    isSaved: false,
    commentsCount: 84,
    audioTrack: {
      title: 'Golden Horizon (Acoustic)',
      artist: 'Novo Amor',
    },
    comments: [
      {
        id: 'c1',
        user: {
          username: 'marcus_creates',
          avatar: MOCK_USERS.marcus.avatar,
        },
        text: 'The color grading in the 2nd shot is unreal! What lens?',
        timestamp: '1h',
        likes: 12,
      },
      {
        id: 'c2',
        user: {
          username: 'alex_creator',
          avatar: CURRENT_USER.avatar,
        },
        text: 'Pure magic Sophia! Need to add this to my bucket list 🏔️',
        timestamp: '45m',
        likes: 6,
      },
    ],
  },
  {
    id: 'post_2',
    author: MOCK_USERS.tokyo,
    media: [
      {
        id: 'm2_1',
        url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1000&auto=format&fit=crop&q=80',
        type: 'image',
      },
      {
        id: 'm2_2',
        url: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=1000&auto=format&fit=crop&q=80',
        type: 'image',
      },
    ],
    caption: 'Rainy midnight in Shinjuku. Reflections on wet asphalt hit differently through 35mm glass. ☔🏮',
    location: 'Shinjuku, Tokyo',
    timestamp: '5 hours ago',
    likesCount: 8940,
    isLiked: true,
    isSaved: true,
    commentsCount: 42,
    audioTrack: {
      title: 'Midnight City Dreams',
      artist: 'Kavinsky',
    },
    comments: [
      {
        id: 'c3',
        user: {
          username: 'luna_designs',
          avatar: MOCK_USERS.luna.avatar,
        },
        text: 'The cinematic atmosphere is unmatched 🖤',
        timestamp: '3h',
        likes: 18,
      },
    ],
  },
  {
    id: 'post_3',
    author: MOCK_USERS.marcus,
    media: [
      {
        id: 'm3_1',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&auto=format&fit=crop&q=80',
        type: 'image',
      },
      {
        id: 'm3_2',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1000&auto=format&fit=crop&q=80',
        type: 'image',
      },
      {
        id: 'm3_3',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1000&auto=format&fit=crop&q=80',
        type: 'image',
      },
    ],
    caption: 'Cantilevered concrete, natural oak, and floor-to-ceiling glass. Balancing raw brutalism with organic warmth in our latest residential build.',
    location: 'Kyoto, Japan',
    timestamp: '9 hours ago',
    likesCount: 6510,
    isLiked: false,
    isSaved: false,
    commentsCount: 31,
    comments: [
      {
        id: 'c4',
        user: {
          username: 'chef_marco',
          avatar: MOCK_USERS.chef.avatar,
        },
        text: 'That kitchen island is a dream! 👏',
        timestamp: '7h',
        likes: 4,
      },
    ],
  },
  {
    id: 'post_4',
    author: MOCK_USERS.chef,
    media: [
      {
        id: 'm4_1',
        url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1000&auto=format&fit=crop&q=80',
        type: 'image',
      },
      {
        id: 'm4_2',
        url: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=1000&auto=format&fit=crop&q=80',
        type: 'image',
      },
    ],
    caption: 'Handmade saffron tagliolini with wild chanterelles and aged 36-month Parmigiano-Reggiano. Pure simplicity cooked with respect for the season. 🍝',
    location: 'Florence, Italy',
    timestamp: '1 day ago',
    likesCount: 11200,
    isLiked: false,
    isSaved: false,
    commentsCount: 76,
    comments: [],
  },
];

export const INITIAL_STORIES: UserStory[] = [
  {
    user: CURRENT_USER,
    hasUnseen: false,
    items: [
      {
        id: 's_curr_1',
        mediaUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80',
        mediaType: 'image',
        timestamp: '3h ago',
        caption: 'Studio session testing new natural lighting setups 📷✨',
      },
    ],
  },
  {
    user: MOCK_USERS.sophia,
    hasUnseen: true,
    items: [
      {
        id: 's1_1',
        mediaUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
        mediaType: 'image',
        timestamp: '1h ago',
        caption: 'Morning dip before catching the ferry 🌊☀️',
      },
      {
        id: 's1_2',
        mediaUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&auto=format&fit=crop&q=80',
        mediaType: 'image',
        timestamp: '45m ago',
        caption: 'Santorini cliffside views are unmatched! 🇬🇷',
      },
    ],
  },
  {
    user: MOCK_USERS.tokyo,
    hasUnseen: true,
    items: [
      {
        id: 's2_1',
        mediaUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&auto=format&fit=crop&q=80',
        mediaType: 'image',
        timestamp: '4h ago',
        caption: 'Akihabara retro game hunt 🕹️',
      },
    ],
  },
  {
    user: MOCK_USERS.luna,
    hasUnseen: true,
    items: [
      {
        id: 's3_1',
        mediaUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&auto=format&fit=crop&q=80',
        mediaType: 'image',
        timestamp: '6h ago',
        caption: 'Unloading fresh stoneware from the kiln! 🍵',
      },
    ],
  },
  {
    user: MOCK_USERS.chef,
    hasUnseen: false,
    items: [
      {
        id: 's4_1',
        mediaUrl: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&auto=format&fit=crop&q=80',
        mediaType: 'image',
        timestamp: '12h ago',
        caption: 'Prep work for tonight’s tasting menu 🔪',
      },
    ],
  },
];

export const INITIAL_REELS: Reel[] = [
  {
    id: 'reel_1',
    author: MOCK_USERS.sophia,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-coming-to-the-beach-5016-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    caption: 'That feeling when you arrive at a secluded cove in Greece without a soul in sight 💙🌊 #travel #wanderlust #islandlife',
    audioTrack: {
      title: 'Ocean Breeze (Sped Up)',
      artist: 'Sophia Bennett • Original Audio',
    },
    likesCount: 84200,
    isLiked: false,
    commentsCount: 523,
    sharesCount: 1420,
    isSaved: false,
    comments: [
      {
        id: 'rc1',
        user: { username: 'alex_creator', avatar: CURRENT_USER.avatar },
        text: 'The water clarity is incredible!',
        timestamp: '2h',
        likes: 42,
      },
    ],
  },
  {
    id: 'reel_2',
    author: MOCK_USERS.tokyo,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-rain-falling-on-the-water-of-a-lake-seen-up-close-18312-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&auto=format&fit=crop&q=80',
    caption: 'Cyberpunk rainy Tokyo vibes. Every puddle is a reflection of another world 🌧️ neon glow all night long.',
    audioTrack: {
      title: 'Midnight Synth Echoes',
      artist: 'Kenji Takahashi • Original Audio',
    },
    likesCount: 132000,
    isLiked: true,
    commentsCount: 890,
    sharesCount: 3820,
    isSaved: true,
    comments: [],
  },
  {
    id: 'reel_3',
    author: MOCK_USERS.chef,
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-cutting-fresh-vegetables-on-a-wooden-board-43098-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
    caption: 'Knife skills 101: Julienning seasonal herbs in under 15 seconds. Chef secrets! 👨‍🍳🔥 #cheflife #cooking #culinary',
    audioTrack: {
      title: 'Italian Kitchen Rhythm',
      artist: 'Marco DeLuca • Audio',
    },
    likesCount: 47900,
    isLiked: false,
    commentsCount: 312,
    sharesCount: 820,
    isSaved: false,
    comments: [],
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 'note_curr',
    user: CURRENT_USER,
    content: 'Editing new portfolio shots 📸✨',
    musicTrack: {
      title: 'Espresso',
      artist: 'Sabrina Carpenter',
    },
    timestamp: '2h ago',
  },
  {
    id: 'note_1',
    user: MOCK_USERS.sophia,
    content: 'Boarding flight to Bali! 🌴✈️',
    musicTrack: {
      title: 'Golden Hour',
      artist: 'JVKE',
    },
    timestamp: '1h ago',
  },
  {
    id: 'note_2',
    user: MOCK_USERS.marcus,
    content: 'Need more coffee for blueprints ☕📐',
    musicTrack: {
      title: 'Lo-Fi Chill Beats',
      artist: 'Chillhop Music',
    },
    timestamp: '3h ago',
  },
  {
    id: 'note_3',
    user: MOCK_USERS.tokyo,
    content: 'Midnight ramen run 🍜',
    timestamp: '5h ago',
  },
  {
    id: 'note_4',
    user: MOCK_USERS.luna,
    content: 'Clay is drying fast today 🏺',
    musicTrack: {
      title: 'Sunday Morning',
      artist: 'Maroon 5',
    },
    timestamp: '6h ago',
  },
];

export const INITIAL_CHATS: ChatThread[] = [
  {
    id: 'chat_sophia',
    participant: MOCK_USERS.sophia,
    unreadCount: 1,
    lastMessage: {
      id: 'm_s_last',
      senderId: 'user_sophia',
      text: 'Sent you a disappearing photo of the bay!',
      instant: {
        id: 'inst_1',
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
        viewMode: 'view_once',
        isViewed: false,
        senderId: 'user_sophia',
        timestamp: '10:42 AM',
      },
      timestamp: '10:42 AM',
      status: 'delivered',
    },
    messages: [
      {
        id: 'm1',
        senderId: 'user_current',
        text: 'Hey Sophia! How was the hike yesterday?',
        timestamp: '10:30 AM',
        status: 'read',
      },
      {
        id: 'm2',
        senderId: 'user_sophia',
        text: 'It was breathtaking! The fog rolled in right as the sun set over the peaks.',
        timestamp: '10:35 AM',
        status: 'read',
      },
      {
        id: 'm3',
        senderId: 'user_sophia',
        text: 'Look at this instant preview before I post it!',
        instant: {
          id: 'inst_1',
          imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
          viewMode: 'view_once',
          isViewed: false,
          senderId: 'user_sophia',
          timestamp: '10:42 AM',
        },
        timestamp: '10:42 AM',
        status: 'delivered',
      },
    ],
  },
  {
    id: 'chat_marcus',
    participant: MOCK_USERS.marcus,
    unreadCount: 0,
    lastMessage: {
      id: 'm_m_last',
      senderId: 'user_current',
      text: 'Let me know what you think of the mood board.',
      timestamp: 'Yesterday',
      status: 'read',
    },
    messages: [
      {
        id: 'mm1',
        senderId: 'user_marcus',
        text: 'Alex, did you see the new architectural gallery in Soho?',
        timestamp: 'Yesterday',
        status: 'read',
      },
      {
        id: 'mm2',
        senderId: 'user_current',
        text: 'Yes! The brutalist staircase was stunning.',
        timestamp: 'Yesterday',
        status: 'read',
      },
    ],
  },
  {
    id: 'chat_tokyo',
    participant: MOCK_USERS.tokyo,
    unreadCount: 0,
    lastMessage: {
      id: 'm_t_last',
      senderId: 'user_tokyo',
      text: 'Heading out for night photography now!',
      timestamp: '2d ago',
      status: 'read',
    },
    messages: [
      {
        id: 'mt1',
        senderId: 'user_tokyo',
        text: 'Heading out for night photography now!',
        timestamp: '2d ago',
        status: 'read',
      },
    ],
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    title: 'Minimalist Ceramic Pour-Over Set',
    brand: 'Studio Kinfolk',
    brandAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    price: 48.00,
    originalPrice: 62.00,
    rating: 4.9,
    reviewsCount: 184,
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Hand-thrown speckled stoneware dripper with matching 500ml server. Designed for precise extraction and timeless countertop appeal.',
    category: 'Home',
    inStock: true,
    tags: ['Ceramics', 'Coffee', 'Handcrafted', 'Kitchen'],
  },
  {
    id: 'prod_2',
    title: 'Vintage Leather Camera Strap',
    brand: 'Leica Craft Works',
    brandAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    price: 65.00,
    rating: 4.8,
    reviewsCount: 312,
    images: [
      'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Full-grain vegetable-tanned leather strap with brass split rings and scratch guards. Ages beautifully with rich patina.',
    category: 'Accessories',
    inStock: true,
    tags: ['Photography', 'Leather', 'Vintage', 'Gear'],
  },
  {
    id: 'prod_3',
    title: 'Oversized Washed Linen Chore Jacket',
    brand: 'Atelier Monochrome',
    brandAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    price: 125.00,
    originalPrice: 150.00,
    rating: 4.7,
    reviewsCount: 94,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Breathable heavyweight European flax linen with horn buttons and three deep patch pockets. Relaxed, gender-neutral fit.',
    category: 'Apparel',
    inStock: true,
    tags: ['Clothing', 'Linen', 'Sustainable', 'Minimalist'],
  },
  {
    id: 'prod_4',
    title: 'Mechanical Keychron Wireless Keyboard',
    brand: 'Nordic Desk Studio',
    brandAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    price: 89.00,
    rating: 4.9,
    reviewsCount: 540,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541140532154-b024d705b909?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'Hot-swappable custom switches, aluminum frame, Bluetooth 5.1 multi-device pairing, and warm LED backlighting.',
    category: 'Tech',
    inStock: true,
    tags: ['Tech', 'Desk Setup', 'Mechanical', 'Minimalist'],
  },
  {
    id: 'prod_5',
    title: 'Botanical Clay Face Mask & Serum Duo',
    brand: 'Terra Botanica',
    brandAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    price: 42.00,
    rating: 4.9,
    reviewsCount: 220,
    images: [
      'https://images.unsplash.com/photo-1608248597359-0524458f4a13?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'French green clay paired with cold-pressed rosehip seed oil. Detoxifies pores while delivering deep, glowing hydration.',
    category: 'Beauty',
    inStock: true,
    tags: ['Skincare', 'Clean Beauty', 'Organic'],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n1',
    type: 'like',
    user: MOCK_USERS.sophia,
    postThumbnail: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=100&auto=format&fit=crop&q=80',
    text: 'liked your photo: "Studio session testing new natural lighting setups".',
    timestamp: '20m ago',
    isRead: false,
  },
  {
    id: 'n2',
    type: 'comment',
    user: MOCK_USERS.marcus,
    postThumbnail: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=100&auto=format&fit=crop&q=80',
    text: 'commented: "The color grading in the 2nd shot is unreal! What lens?"',
    timestamp: '1h ago',
    isRead: false,
  },
  {
    id: 'n3',
    type: 'follow',
    user: MOCK_USERS.luna,
    text: 'started following you.',
    timestamp: '3h ago',
    isRead: true,
  },
  {
    id: 'n4',
    type: 'mention',
    user: MOCK_USERS.tokyo,
    postThumbnail: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=100&auto=format&fit=crop&q=80',
    text: 'mentioned you in a reel: "Collab night shoot with @alex_creator coming soon!"',
    timestamp: '5h ago',
    isRead: true,
  },
];
